backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_library:
  name: cloudinary
  config:
    cloud_name: dfthmjy1i
    api_key: 828742897268572
    default_transformations:
      - - fetch_format: auto
          width: 300
          quality: auto
          crop: scale

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Slug", name: "slug", required: true, widget: "string" }
      - { label: "Title", name: "title", required: true, widget: "string" }
      - { label: "Author", name: "author", required: true, widget: "string" }
      - { label: "Publish Date", name: "date", required: true, widget: "datetime" }
      - { label: "Description", name: "description", required: true, widget: "string" }
      - { label: "Image", name: "image", required: true, widget: "image", choose_url: "false" }
      - { label: "Description of Image", name: "imageAlt", required: true, widget: "string" }
      - { label: "Body", name: "body", required: true, widget: "markdown" }


